"""Which rules to switch off for which kinds of file.

Some files are generated by tools rather than written by people, and are full
of content that looks like a secret without being one: lockfile checksums, the
coordinates in an SVG, the body of a certificate. Each case here switches off
only the rules that misfire on that kind of file, never the whole file.
"""

from __future__ import annotations

import os
import re

DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
DEFAULT_EXCLUDED_DIR_NAMES = {
    ".git",
    "node_modules",
    ".venv",
    "venv",
    "__pycache__",
    "dist",
    "build",
    # Local tool caches. Gitignored, but a directory scan walks the filesystem
    # regardless of git status, and cached artifacts here trip the entropy
    # detector.
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".hypothesis",
}


# Machine-generated dependency manifests, which are overwhelmingly base64
# integrity hashes. Entropy cannot tell those from a credential.
DEFAULT_LOCKFILE_NAMES = frozenset(
    {
        "go.sum",
        "package-lock.json",
        "npm-shrinkwrap.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "bun.lock",
        "deno.lock",
        "Cargo.lock",
        ".cargo-checksum.json",
        "poetry.lock",
        "Pipfile.lock",
        "pdm.lock",
        "uv.lock",
        "composer.lock",
        "Gemfile.lock",
        "packages.lock.json",
        "gradle.lockfile",
        "flake.lock",
        "pubspec.lock",
        "mix.lock",
        "conan.lock",
        "cabal.project.freeze",
    }
)

# The two detectors that fire on shape alone, with no vendor prefix or checksum
# behind them. They are what has to come off in files full of random-looking
# text.
GUESSING_RULE_IDS = frozenset({"high-entropy-string", "generic-secret"})


# SVG path data is a stream of coordinates, and four dot-separated numbers in a
# row parse as an IPv4 address. Only ipv4 misfires here, so only ipv4 comes off.
_DRAWING_FILE_TYPES = frozenset({".svg"})
_RULES_TO_SKIP_IN_DRAWINGS = frozenset({"ipv4"})


def _rules_to_skip_for_file(path: str | None, disabled: frozenset[str]) -> frozenset[str]:
    """Rules to switch off for this file, on top of the config-disabled ones."""
    if path is None:
        return disabled
    name = os.path.basename(path)
    if name in DEFAULT_LOCKFILE_NAMES:
        return disabled | GUESSING_RULE_IDS
    if os.path.splitext(name)[1].lower() in _DRAWING_FILE_TYPES:
        return disabled | _RULES_TO_SKIP_IN_DRAWINGS
    return disabled


# A certificate is public by design, but its base64 body is indistinguishable
# from a private key's by entropy alone.
_PEM_BLOCK_RE = re.compile(r"-----BEGIN ([A-Z0-9 ]+)-----.*?-----END \1-----", re.DOTALL)


def _public_certificate_ranges(text: str) -> list[tuple[int, int]]:
    """Spans of PEM blocks that carry nothing secret.

    Blocks labelled PRIVATE KEY are excluded, so `pem-private-key` still
    reports them. That rule matches on the label rather than on entropy, so
    nothing here affects it.
    """
    if "-----BEGIN " not in text:  # cheap guard: the DOTALL scan is not free
        return []
    return [
        (m.start(), m.end())
        for m in _PEM_BLOCK_RE.finditer(text)
        if "PRIVATE KEY" not in m.group(1)
    ]
